const BASE_URL = window._env_?.BACKEND_URL || "http://localhost:5000/api";

const API_ROUTES = {
  getStudent: `${BASE_URL}/student/get`,
  getColleges: `${BASE_URL}/college/get-colleges`,
  getAllStudents: `${BASE_URL}/student/getStudents`,
  studentLogout: `${BASE_URL}/auth/logout`,
  adminLogout: `${BASE_URL}/auth/admin-logout`,
  addScholarship: `${BASE_URL}/scholarship/add`,
  getAllScholarships: `${BASE_URL}/scholarship/fetch-all`,
  approveScholarship: `${BASE_URL}/scholarship/approve-students`,
  admissionForm: `${BASE_URL}/student/fill-details`,
  getCourses: `${BASE_URL}/course/get-courses`,
  getOtherAdminsCredential: `${BASE_URL}/admin/credential`,
  updateAdminsPassword: `${BASE_URL}/admin/update-password`,
  addCollege: `${BASE_URL}/college/add`,
  adminLogin: `${BASE_URL}/auth/admin-login`,
  studentLogin: `${BASE_URL}/auth/login`,
  adminRegister: `${BASE_URL}/auth/admin-register`,
  studentRegister: `${BASE_URL}/auth/register`,
  adminOtpVerify: `${BASE_URL}/auth/admin-verify-otp`,
  studentOtpVerify: `${BASE_URL}/auth/verify-otp`,
  getStudentsDetails: `${BASE_URL}/student/getStudentsDetails`,
  getGrievances: `${BASE_URL}/grievance/fetch-grievances`,
  getLeaves: `${BASE_URL}/leave/fetch-leaves`,
  getAdmin: `${BASE_URL}/admin/get`,
  addGrievance: `${BASE_URL}/grievance/add`,
  addLeave: `${BASE_URL}/leave/add`,
  getScholarshipParticipation: `${BASE_URL}/scholarship/participate`,
  resolveGrievance: (grievanceId: string) => `${BASE_URL}/grievance/resolve-grievance/${grievanceId}`,
  approveLeave: (leaveId: string) => `${BASE_URL}/leave/approve-leave/${leaveId}`,
  rejectLeave: (leaveId: string) => `${BASE_URL}/leave/reject-leave/${leaveId}`,
  getScholarshipById: (scholarshipId: string) => `${BASE_URL}/scholarship/fetch-students/${scholarshipId}`,
  getLeaveById: (studentId: string) => `${BASE_URL}/leave/fetch-leave-student/${studentId}`,
  getStudentAppliedForScholarship: (studentId: string) => `${BASE_URL}/scholarship/fetch-participated/${studentId}`,
  getStudentNotAppliedForScholarship: (studentId: string) => `${BASE_URL}/scholarship/fetch-non-participated/${studentId}`,
  getCollegeById: (collegeId: string) => `${BASE_URL}/college/getCollegeById/${collegeId}`,
  getGrievanceStudents: (studentId: string) => `${BASE_URL}/grievance/fetch-grievance-student/${studentId}`,
};

export { BASE_URL, API_ROUTES };
